"""Proxy auto-provisioning engine — generates hardsession proxies from @bpproxy_bot.

Integrates with the BulletProof Proxy Telegram bot via Telethon using pre-authorized
TG sessions.  On demand it walks the bot menu (/start → Русский → согласен → бонус →
меню → Ротационные → Residential/Datacenter → Сессия → Получить прокси), extracts
the proxy URL from the bot reply, and stores it in the proxy pool (SQLite).

The engine is fully async and designed to be called from the FastAPI task runtime
or directly from any async context:

    provisioner = ProxyProvisioner()
    result = await provisioner.provision(count=5, proxy_type="residential")

Source: ported from C:/Users/User/tmp/mass_bpproxy.py and bpproxy_bot.py.
"""
from __future__ import annotations

import asyncio
import glob
import json
import logging
import os
import random
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BOT_USERNAME = "@bpproxy_bot"
DEFAULT_API_ID = 2040
DEFAULT_API_HASH = "b18441a1ff607e10a989891a5462e627"

# Directories containing pre-authorized Telethon *.session files.
# Override via env BPPROXY_SESSIONS_DIRS (os.pathsep-separated).
_DEFAULT_SESSIONS_DIRS = [
    r"C:\Users\User\Desktop\_PROJECTS\рассылка\sessions",
    r"C:\Users\User\Desktop\_PROJECTS\рассылка\sessions2",
    r"C:\Users\User\Desktop\_PROJECTS\рассылка\sessions3",
    r"C:\Users\User\Desktop\_PROJECTS\рассылка\sessions4",
    r"C:\Users\User\Desktop\_PROJECTS\рассылка\sessions5",
]

# Matches proxy URLs emitted by the bot:  http://bpuser-XXX@host:port
PROXY_RE = re.compile(r"(https?://bpuser-[^\s`]+@[\w.-]+:\d+)")

# Bot menu navigation delays (seconds).  Kept short for speed but long enough
# for the bot to respond.
_NAV_WAIT = 4
_CLICK_WAIT = 4
_EXTRACT_WAIT = 5
_START_WAIT = 3


def _sessions_dirs() -> list[str]:
    env = os.environ.get("BPPROXY_SESSIONS_DIRS", "")
    if env:
        return [d.strip() for d in env.split(os.pathsep) if d.strip()]
    return _DEFAULT_SESSIONS_DIRS


def _load_session_meta(sess_path: str) -> tuple[int, str]:
    """Load api_id / api_hash from the sibling .json file, fall back to defaults."""
    json_path = sess_path.replace(".session", ".json")
    api_id = DEFAULT_API_ID
    api_hash = DEFAULT_API_HASH
    if os.path.exists(json_path):
        try:
            with open(json_path, "r", encoding="utf-8") as fh:
                meta = json.load(fh)
            api_id = int(meta.get("app_id") or meta.get("api_id") or DEFAULT_API_ID)
            api_hash = meta.get("app_hash") or meta.get("api_hash") or DEFAULT_API_HASH
        except Exception:
            pass
    return api_id, api_hash


def _collect_sessions() -> list[str]:
    """Glob all *.session files from configured directories."""
    sessions: list[str] = []
    for d in _sessions_dirs():
        sessions.extend(glob.glob(os.path.join(d, "*.session")))
    return sessions


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class ProvisionedProxy:
    """A single proxy generated by the bot."""
    url: str
    proxy_type: str          # "residential" | "datacenter"
    phone: str               # TG session phone that generated it
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict:
        return {
            "url": self.url,
            "type": self.proxy_type,
            "phone": self.phone,
            "created_at": self.created_at.isoformat(),
        }


@dataclass
class ProvisionResult:
    """Aggregate result of a provisioning run."""
    requested: int
    generated: list[ProvisionedProxy] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)

    @property
    def success_count(self) -> int:
        return len(self.generated)

    def to_dict(self) -> dict:
        return {
            "requested": self.requested,
            "generated": [p.to_dict() for p in self.generated],
            "errors": self.errors,
            "success_count": self.success_count,
        }


# ---------------------------------------------------------------------------
# Bot interaction helpers (ported from mass_bpproxy.py / bpproxy_bot.py)
# ---------------------------------------------------------------------------

async def _click_button(client, entity, button_text: str, wait: float = _CLICK_WAIT) -> bool:
    """Find the latest bot message with a button matching *button_text* and click it."""
    best_msg = None
    best_btn = None
    async for msg in client.iter_messages(entity, limit=20):
        if msg.sender_id != entity.id or not msg.buttons:
            continue
        for row in msg.buttons:
            for btn in row:
                btn_text = btn.text if hasattr(btn, "text") else str(btn)
                if button_text.lower() in btn_text.lower():
                    if best_msg is None or msg.id > best_msg.id:
                        best_msg = msg
                        best_btn = btn
                    break
    if not best_msg or not best_btn:
        return False
    try:
        await best_btn.click()
        await asyncio.sleep(wait)
        return True
    except Exception as exc:
        logger.debug("click_button %r failed: %s", button_text, exc)
        return False


async def _extract_proxy(client, entity, after_id: int) -> Optional[str]:
    """Look for a proxy string in bot messages newer than *after_id*."""
    async for msg in client.iter_messages(entity, min_id=after_id, limit=5):
        if msg.sender_id != entity.id:
            continue
        m = PROXY_RE.search(msg.text or "")
        if m:
            return m.group(1)
    return None


async def _get_latest_msg_id(client, entity) -> int:
    async for msg in client.iter_messages(entity, limit=1):
        return msg.id
    return 0


async def _navigate_to_rotational(client, entity) -> bool:
    """Run the onboarding flow: /start → Русский → согласен → бонус → меню → Ротационные.

    Returns True if we successfully reached the rotational proxy submenu.
    """
    # /start
    await client.send_message(entity, "/start")
    await asyncio.sleep(_START_WAIT)

    # Русский (language selection — only on first contact)
    await _click_button(client, entity, "Русский", wait=_NAV_WAIT)

    # согласен (terms acceptance)
    await _click_button(client, entity, "согласен", wait=_NAV_WAIT)

    # Получить бонус (free trial bonus)
    await _click_button(client, entity, "Получить бонус", wait=_NAV_WAIT)

    # Открыть меню
    ok = await _click_button(client, entity, "Открыть меню", wait=_NAV_WAIT)
    if not ok:
        # Maybe already in menu — retry /start
        await client.send_message(entity, "/start")
        await asyncio.sleep(_START_WAIT)
        await _click_button(client, entity, "Открыть меню", wait=_NAV_WAIT)

    # Ротационные
    ok = await _click_button(client, entity, "Ротационные", wait=_NAV_WAIT)
    if not ok:
        logger.warning("navigate_to_rotational: no 'Ротационные' button")
        return False
    return True


async def _acquire_one_type(
    client, entity, proxy_type: str
) -> Optional[str]:
    """From the rotational submenu, acquire a single hardsession proxy of *proxy_type*.

    *proxy_type* must be "Residential" or "Datacenter" (case-insensitive match on
    button text).  Assumes we are currently in the rotational submenu.
    """
    # Click the proxy type button
    ok = await _click_button(client, entity, proxy_type, wait=_NAV_WAIT)
    if not ok:
        logger.warning("acquire_one_type: no %r button", proxy_type)
        return None

    # Switch to hardsession mode (Сессия)
    await _click_button(client, entity, "Сессия", wait=_NAV_WAIT)

    # Record msg id before requesting, so we can find the new proxy message
    before_id = await _get_latest_msg_id(client, entity)

    # Получить прокси
    ok = await _click_button(client, entity, "Получить прокси", wait=_EXTRACT_WAIT)
    if not ok:
        logger.warning("acquire_one_type: no 'Получить прокси' button for %s", proxy_type)
        return None

    proxy = await _extract_proxy(client, entity, before_id)
    if not proxy:
        logger.warning("acquire_one_type: no proxy string found for %s", proxy_type)
    return proxy


async def _process_session(
    sess_path: str,
    api_id: int,
    api_hash: str,
    phone: str,
    want_residential: bool,
    want_datacenter: bool,
) -> list[ProvisionedProxy]:
    """Full flow for one TG session: onboarding + hardsession proxies.

    Returns a list of ProvisionedProxy objects (0–2 entries).
    """
    from telethon import TelegramClient

    client = TelegramClient(sess_path, api_id, api_hash)
    await client.connect()
    if not await client.is_user_authorized():
        logger.debug("session %s not authorized — skipping", phone)
        await client.disconnect()
        return []

    entity = await client.get_entity(BOT_USERNAME)
    results: list[ProvisionedProxy] = []

    try:
        if not await _navigate_to_rotational(client, entity):
            return []

        # --- Residential ---
        if want_residential:
            proxy = await _acquire_one_type(client, entity, "Residential")
            if proxy:
                results.append(ProvisionedProxy(
                    url=proxy, proxy_type="residential", phone=phone,
                ))
                logger.info("[%s] RES: %s", phone, proxy)

        # --- Datacenter ---
        if want_datacenter:
            # Go back to rotational submenu
            await _click_button(client, entity, "Назад", wait=_NAV_WAIT)
            # If Назад didn't work, re-navigate
            if not await _click_button(client, entity, "Datacenter", wait=_NAV_WAIT):
                await _click_button(client, entity, "Назад", wait=_NAV_WAIT)
                await _click_button(client, entity, "Ротационные", wait=_NAV_WAIT)

            proxy = await _acquire_one_type(client, entity, "Datacenter")
            if proxy:
                results.append(ProvisionedProxy(
                    url=proxy, proxy_type="datacenter", phone=phone,
                ))
                logger.info("[%s] DC:  %s", phone, proxy)

    except Exception as exc:
        logger.error("session %s error: %s", phone, exc)
    finally:
        await client.disconnect()

    return results


# ---------------------------------------------------------------------------
# Session discovery
# ---------------------------------------------------------------------------

async def _find_authorized_sessions(count: int) -> list[tuple[str, int, str, str]]:
    """Find *count* authorized sessions.  Returns [(path, api_id, api_hash, phone)]."""
    sessions = _collect_sessions()
    random.shuffle(sessions)
    result: list[tuple[str, int, str, str]] = []
    for sess_path in sessions:
        if len(result) >= count:
            break
        api_id, api_hash = _load_session_meta(sess_path)
        phone = os.path.basename(sess_path).replace(".session", "")
        try:
            from telethon import TelegramClient
            client = TelegramClient(sess_path, api_id, api_hash)
            await client.connect()
            if await client.is_user_authorized():
                result.append((sess_path, api_id, api_hash, phone))
                logger.debug("found authorized session: %s", phone)
            await client.disconnect()
        except Exception:
            pass
    return result


# ---------------------------------------------------------------------------
# DB integration
# ---------------------------------------------------------------------------

def _store_proxies(proxies: list[ProvisionedProxy]) -> int:
    """Store provisioned proxies in the SQLite proxy pool.

    Uses a lazy import so the provisioner can run standalone without the DB
    module being present.  Returns the number of proxies actually stored
    (duplicates are skipped).
    """
    if not proxies:
        return 0

    try:
        from sqlmodel import Session as DBSession, select
        from core.db import ProxyModel, engine
    except Exception:
        # DB not available — write to fallback file so proxies are not lost
        _fallback_store(proxies)
        return len(proxies)

    stored = 0
    with DBSession(engine) as s:
        for p in proxies:
            existing = s.exec(
                select(ProxyModel).where(ProxyModel.url == p.url)
            ).first()
            if existing:
                # Already in pool — re-activate if it was disabled
                if not existing.is_active:
                    existing.is_active = True
                    s.add(existing)
                continue
            model = ProxyModel(
                url=p.url,
                type=p.proxy_type,
                region="",
                is_active=True,
                last_checked=datetime.now(timezone.utc),
            )
            s.add(model)
            stored += 1
        s.commit()
    logger.info("stored %d new proxies in DB pool", stored)
    return stored


def _fallback_store(proxies: list[ProvisionedProxy]) -> None:
    """Append proxies to a text file when the DB is unavailable."""
    path = os.environ.get(
        "BPPROXY_FALLBACK_FILE",
        os.path.join(os.path.dirname(__file__), "..", "bpproxy_pool.txt"),
    )
    path = os.path.normpath(path)
    with open(path, "a", encoding="utf-8") as f:
        for p in proxies:
            f.write(f"# {p.phone} | {p.proxy_type} | {p.created_at.isoformat()}\n")
            f.write(f"{p.url}\n")
    logger.info("fallback-stored %d proxies to %s", len(proxies), path)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

class ProxyProvisioner:
    """Auto-provisioning engine for @bpproxy_bot hardsession proxies.

    Usage::

        prov = ProxyProvisioner()
        result = await prov.provision(count=5, proxy_type="residential")
        # result.generated → list[ProvisionedProxy]
    """

    async def provision(
        self,
        count: int = 5,
        proxy_type: str = "both",
        store: bool = True,
    ) -> ProvisionResult:
        """Generate *count* hardsession proxies via @bpproxy_bot.

        Args:
            count: Number of TG sessions to use (each yields up to 2 proxies).
            proxy_type: "residential", "datacenter", or "both".
            store: If True, store results in the DB proxy pool.

        Returns:
            ProvisionResult with generated proxies and any errors.
        """
        want_res = proxy_type in ("residential", "both", "all")
        want_dc = proxy_type in ("datacenter", "both", "all")

        result = ProvisionResult(requested=count)

        logger.info("provisioning %d sessions (type=%s)", count, proxy_type)
        sessions = await _find_authorized_sessions(count)
        if not sessions:
            result.errors.append("No authorized TG sessions found")
            return result

        logger.info("found %d authorized sessions", len(sessions))

        for sess_path, api_id, api_hash, phone in sessions:
            try:
                proxies = await _process_session(
                    sess_path, api_id, api_hash, phone,
                    want_residential=want_res,
                    want_datacenter=want_dc,
                )
                result.generated.extend(proxies)
            except Exception as exc:
                result.errors.append(f"{phone}: {exc}")
                logger.error("session %s failed: %s", phone, exc)

        if store and result.generated:
            _store_proxies(result.generated)

        logger.info(
            "provisioning complete: %d/%d proxies from %d sessions, %d errors",
            result.success_count, count * (2 if (want_res and want_dc) else 1),
            len(sessions), len(result.errors),
        )
        return result

    async def provision_residential(self, count: int = 5) -> ProvisionResult:
        """Shortcut: provision only residential hardsession proxies."""
        return await self.provision(count=count, proxy_type="residential")

    async def provision_datacenter(self, count: int = 5) -> ProvisionResult:
        """Shortcut: provision only datacenter hardsession proxies."""
        return await self.provision(count=count, proxy_type="datacenter")

    async def provision_both(self, count: int = 5) -> ProvisionResult:
        """Shortcut: provision both residential + datacenter from each session."""
        return await self.provision(count=count, proxy_type="both")

    async def check_sessions(self) -> dict:
        """Return a summary of available TG sessions.

        Useful for the dashboard / API to show how many sessions are ready.
        """
        all_sessions = _collect_sessions()
        authorized = await _find_authorized_sessions(len(all_sessions))
        return {
            "total_sessions": len(all_sessions),
            "authorized_sessions": len(authorized),
            "sessions_dirs": _sessions_dirs(),
        }


# Module-level singleton for convenience
provisioner = ProxyProvisioner()


# ---------------------------------------------------------------------------
# CLI entry point (mirrors mass_bpproxy.py usage)
# ---------------------------------------------------------------------------

async def _cli() -> None:
    import sys
    count = int(sys.argv[1]) if len(sys.argv) > 1 else 5
    ptype = sys.argv[2] if len(sys.argv) > 2 else "both"
    result = await provisioner.provision(count=count, proxy_type=ptype)
    print(json.dumps(result.to_dict(), indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(_cli())
